export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const RESET_MESSAGES = 'RESET_MESSAGES';

export const SEARCH_MESSAGES = 'SEARCH_MESSAGES';
export const RESET_SEARCH_MESSAGES = 'RESET_SEARCH_MESSAGES';
export const UPDATE_SEARCH_TERMS = 'UPDATE_SEARCH_TERMS';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const UPDATE_NEW_MESSAGE = 'UPDATE_NEW_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';

export const ADD_CHANNEL = 'ADD_CHANNEL';
export const LOAD_CHANNELS = 'LOAD_CHANNELS';
export const SET_CURRENT_CHANNEL = 'SET_CURRENT_CHANNEL';